---
enable_fips: true
firewall_default_drop: false
devsecops_cidr: "100.64.0.0/10"
devsecops_allowed_ports:
  - "22"
  - "3000"
  - "5678"
  - "55555"
  - "8008"
  - "8080"
  - "3023"
  - "3024"
  - "3025"
  - "80"
  - "443"
