# Rename to isr-secondary.yml when using inventory that defines host isr-secondary.

cisco_isr_hostname: isr02
cisco_isr_domain_name: edge.lab

cisco_isr_inside_subinterfaces:
  - vlan: 240
    ipv4: 100.64.240.3
    mask: 255.255.255.0
    description: PLATFORM_CORE_VRRP_secondary
    vrrp:
      group: 240
      vip: 100.64.240.1
      priority: 90
      preempt: true
  - vlan: 244
    ipv4: 100.64.244.3
    mask: 255.255.255.0
    description: GOOGLE_HOME_LAN_VRRP_secondary
    vrrp:
      group: 244
      vip: 100.64.244.1
      priority: 90
      preempt: true

cisco_isr_loopback_config:
  enabled: true
  ipv4: 100.64.242.12
  mask: 255.255.255.255
  description: ISR02_MGMT_LOOPBACK
