---
- name: VRRP IPv4 on tagged inside subinterfaces
  cisco.ios.ios_config:
    parents:
      - "interface {{ cisco_isr_inside_interface }}.{{ item.vlan }}"
    lines:
      - "vrrp {{ item.vrrp.group }} ip {{ item.vrrp.vip }}"
      - "vrrp {{ item.vrrp.group }} priority {{ item.vrrp.priority | default(100) }}"
    save_when: never
  loop: "{{ cisco_isr_inside_subinterfaces | selectattr('vrrp', 'defined') | list }}"
  when: not (cisco_isr_inside_switchport_trunk | bool)
  loop_control:
    label: "VRRP {{ item.vlan }}"

- name: VRRP preempt control (explicit)
  cisco.ios.ios_config:
    parents:
      - "interface {{ cisco_isr_inside_interface }}.{{ item.vlan }}"
    lines:
      - "{{ 'vrrp ' ~ item.vrrp.group|string ~ ' preempt' if (item.vrrp.preempt | default(true) | bool) else ('no vrrp ' ~ item.vrrp.group|string ~ ' preempt') }}"
    save_when: never
  loop: "{{ cisco_isr_inside_subinterfaces | selectattr('vrrp', 'defined') | list }}"
  when: not (cisco_isr_inside_switchport_trunk | bool)
  loop_control:
    label: "VRRP-preempt {{ item.vlan }}"
